export const filterData = [{name:'Fast food',image: require('../Images/fastfood.png'),id:'0'},
                            {name:'Noodles',image: require('../Images/noodles.png'),id:'1'},
                            {name:'Vegetables',image: require('../Images/vegs.png'),id:'2'},
                            {name:'Sea Food',image: require('../Images/seafood.png'),id:'3'},
                            {name:'Bread',image: require('../Images/bread.png'),id:'4'},
                            {name:'Fruits',image: require('../Images/fruits.png'),id:'5'}];

export const restaurantData = [{
    restaurantName:"Mc Donalds",farAway:"21.2",
    businessAddress:"22 Bessie Street",images:'https://images.unsplash.com/photo-1552895638-f7fe08d2f7d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',averageReview:4.1,numberOfReview:288,
    coordinates:{lat: -26.1888612, lng:28.246325}, discount:10,deliveyTime:15,
    collectTime:5,foodType:"Burgers,wraps, milkshakes...",
    productData:[{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships"}],
    id:0},

    {restaurantName:"KFC",farAway:"12.7",
    businessAddress:"22 Bessie Street",images:"https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=867&q=80",averageReview:4.3,numberOfReview:306,
    coordinates:{lat: -26.1891648, lng:28.2441808}, discount:20,deliveyTime:30,
    collectTime:10,foodType:"Chicken, Chicken wings...",
    productData:[{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships"}],
    id:1},

    {restaurantName:"STEERS",farAway:"5",
    businessAddress:"17 olivia Rd, Johannesburg",images:"https://images.unsplash.com/photo-1642616128754-7d026f979317?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",averageReview:4.9,numberOfReview:1272,
    coordinates:{lat: -26.1891648, lng:28.244879}, discount:12,deliveyTime:25,
    collectTime:15,foodType:"Flame grilled beef burgers",
    productData:[{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships"}],
    id:2},

    {restaurantName:"Roman Pizza",farAway:"7",
    businessAddress:"15 Atlas Rd, Kempton Park",
    images:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    averageReview:4.3,numberOfReview:700,
    coordinates:{lat: -26.1845336, lng:28.2481691}, discount:null,deliveyTime:20,
    collectTime:10,foodType:"Chicken pizza, Vegetarian pizza...",
    productData:[{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships"}],
    id:3},

    {restaurantName:"Roman Pizza",farAway:"7",
    businessAddress:"15 Atlas Rd, Kempton Park",
    images:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    averageReview:4.3,numberOfReview:700,
    coordinates:{lat: -26.1845336, lng:28.2481691}, discount:null,deliveyTime:20,
    collectTime:10,foodType:"Chicken pizza, Vegetarian pizza...",
    productData:[{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships"}],
    id:4},
];

export const productData = [{name:"Hand Cut chips",price:29.30,image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:0}, 
    {name:"Big Maiti",price:35.30,image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:1},
    {name:"Chicken Burger",price:39.30,image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:2},
    {name:"Casarole in coselore",price:49.30,image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:3},
    {name:"Fermented Salad",price:59.30,image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:4},
    {name:"dried fried meat",price:69.30,image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Just a deliciously made hand cut ships",id:5}
];

export const menuData = [
    {title:"BEEF",special:false, key:0},
    {title:"CHICKEN",special:false, key:1},
    {title:"VEGGIE BURGER",special:false, key:2},
    {title:"FRIES & CORN",special:false, key:3},
    {title:"SALADS",special:false, key:4},
    {title:"HAPPY MEALS",special:false, key:5},
    {title:"SAHARE BOX",special:false, key:6},
    {title:"MILKSHAKES",special:false, key:7},
    {title:"COLD DRINKS",special:false, key:8},
    {title:"DESSERTS",special:false, key:9},
    {title:"HOT DRINKS",special:false, key:10},
];

export const specialData =[
    {title:"LIMITED OFFER",key:0},
    {title:"GO CHILLI",key:1},
    {title:"GO CHEESE",key:2},
    {title:"CHICKEN DELUXE PROMO",key:3},
        
];

export const menu = [
    {key: 'first', title: 'BEEF'},
    {key: 'second', title: 'CHICKEN'},
    {key: 'third', title: 'VEGGIES'},
    {key: 'fourth', title: 'BURGERS'},
    {key: 'fifth', title: 'FRESHIES'},
    {key: 'sixth', title: 'FRIES'},
    {key: 'seventh', title: 'SIDES'},
    {key: 'eighth', title: 'SHAKES'},
]

export const menuCardData = [
    {
        meal:"Big Mac",
        price:70.00,
        image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        details:"Mcfest features two 100% fresh burger patties that are hot",
        preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
        preferenceData:[
         [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
            {name:"Jalapano Dip",price:8.91,checked:false,id:12},
            {name:"Jalapano Dip",price:8.91,checked:false,id:13},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
            {name:"Jalapano Dip",price:8.91,checked:false,id:15},
            {name:"Jalapano Dip",price:8.91,checked:false,id:16},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
            {name:"Jalapano Dip",price:8.91,checked:false,id:18},
        ],
          [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
          {name:"Jalapano Dip",price:8.91,checked:false,id:21},
          {name:"Jalapano Dip",price:8.91,checked:false,id:22},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
          {name:"Jalapano Dip",price:8.91,checked:false,id:24},
          {name:"Jalapano Dip",price:8.91,checked:false,id:25},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
          {name:"Jalapano Dip",price:8.91,checked:false,id:27},
        ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
        {name:"Jalapano Dip",price:8.91,checked:false,id:30},
          {name:"Jalapano Dip",price:8.91,checked:false,id:31},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
          {name:"Jalapano Dip",price:8.91,checked:false,id:33},
          {name:"Jalapano Dip",price:8.91,checked:false,id:34},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
          {name:"Jalapano Dip",price:8.91,checked:false,id:36},
        ],

          [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
          {name:"Jalapano Dip",price:8.91,checked:false,id:39},
          {name:"Jalapano Dip",price:8.91,checked:false,id:40},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
          {name:"Jalapano Dip",price:8.91,checked:false,id:42},
          {name:"Jalapano Dip",price:8.91,checked:false,id:43},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
          {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
        ],
    ],
        minimum_quantity:[2,1,1,null,null],
        counter:[0,0,0,0,0],
        required: [true,true,true,false,false],
        id:1
    },

    {
        meal:"Big Mac",
        price:70.00,
        image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        details:"Mcfest features two 100% fresh burger patties that are hot",
        preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
        preferenceData:[
         [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
            {name:"Jalapano Dip",price:8.91,checked:false,id:12},
            {name:"Jalapano Dip",price:8.91,checked:false,id:13},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
            {name:"Jalapano Dip",price:8.91,checked:false,id:15},
            {name:"Jalapano Dip",price:8.91,checked:false,id:16},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
            {name:"Jalapano Dip",price:8.91,checked:false,id:18},
        ],
          [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
          {name:"Jalapano Dip",price:8.91,checked:false,id:21},
          {name:"Jalapano Dip",price:8.91,checked:false,id:22},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
          {name:"Jalapano Dip",price:8.91,checked:false,id:24},
          {name:"Jalapano Dip",price:8.91,checked:false,id:25},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
          {name:"Jalapano Dip",price:8.91,checked:false,id:27},
        ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
        {name:"Jalapano Dip",price:8.91,checked:false,id:30},
          {name:"Jalapano Dip",price:8.91,checked:false,id:31},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
          {name:"Jalapano Dip",price:8.91,checked:false,id:33},
          {name:"Jalapano Dip",price:8.91,checked:false,id:34},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
          {name:"Jalapano Dip",price:8.91,checked:false,id:36},
        ],

          [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
          {name:"Jalapano Dip",price:8.91,checked:false,id:39},
          {name:"Jalapano Dip",price:8.91,checked:false,id:40},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
          {name:"Jalapano Dip",price:8.91,checked:false,id:42},
          {name:"Jalapano Dip",price:8.91,checked:false,id:43},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
          {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
        ],
    ],
        minimum_quantity:[2,1,1,null,null],
        counter:[0,0,0,0,0],
        required: [true,true,true,false,false],
        id:2
    },

    {
        meal:"Big Mac",
        price:70.00,
        image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        details:"Mcfest features two 100% fresh burger patties that are hot",
        preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
        preferenceData:[
         [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
            {name:"Jalapano Dip",price:8.91,checked:false,id:12},
            {name:"Jalapano Dip",price:8.91,checked:false,id:13},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
            {name:"Jalapano Dip",price:8.91,checked:false,id:15},
            {name:"Jalapano Dip",price:8.91,checked:false,id:16},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
            {name:"Jalapano Dip",price:8.91,checked:false,id:18},
        ],
          [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
          {name:"Jalapano Dip",price:8.91,checked:false,id:21},
          {name:"Jalapano Dip",price:8.91,checked:false,id:22},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
          {name:"Jalapano Dip",price:8.91,checked:false,id:24},
          {name:"Jalapano Dip",price:8.91,checked:false,id:25},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
          {name:"Jalapano Dip",price:8.91,checked:false,id:27},
        ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
        {name:"Jalapano Dip",price:8.91,checked:false,id:30},
          {name:"Jalapano Dip",price:8.91,checked:false,id:31},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
          {name:"Jalapano Dip",price:8.91,checked:false,id:33},
          {name:"Jalapano Dip",price:8.91,checked:false,id:34},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
          {name:"Jalapano Dip",price:8.91,checked:false,id:36},
        ],

          [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
          {name:"Jalapano Dip",price:8.91,checked:false,id:39},
          {name:"Jalapano Dip",price:8.91,checked:false,id:40},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
          {name:"Jalapano Dip",price:8.91,checked:false,id:42},
          {name:"Jalapano Dip",price:8.91,checked:false,id:43},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
          {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
        ],
    ],
        minimum_quantity:[2,1,1,null,null],
        counter:[0,0,0,0,0],
        required: [true,true,true,false,false],
        id:3
    },
    {
        meal:"Big Mac",
        price:70.00,
        image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        details:"Mcfest features two 100% fresh burger patties that are hot",
        preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
        preferenceData:[
         [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
            {name:"Jalapano Dip",price:8.91,checked:false,id:12},
            {name:"Jalapano Dip",price:8.91,checked:false,id:13},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
            {name:"Jalapano Dip",price:8.91,checked:false,id:15},
            {name:"Jalapano Dip",price:8.91,checked:false,id:16},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
            {name:"Jalapano Dip",price:8.91,checked:false,id:18},
        ],
          [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
          {name:"Jalapano Dip",price:8.91,checked:false,id:21},
          {name:"Jalapano Dip",price:8.91,checked:false,id:22},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
          {name:"Jalapano Dip",price:8.91,checked:false,id:24},
          {name:"Jalapano Dip",price:8.91,checked:false,id:25},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
          {name:"Jalapano Dip",price:8.91,checked:false,id:27},
        ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
        {name:"Jalapano Dip",price:8.91,checked:false,id:30},
          {name:"Jalapano Dip",price:8.91,checked:false,id:31},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
          {name:"Jalapano Dip",price:8.91,checked:false,id:33},
          {name:"Jalapano Dip",price:8.91,checked:false,id:34},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
          {name:"Jalapano Dip",price:8.91,checked:false,id:36},
        ],

          [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
          {name:"Jalapano Dip",price:8.91,checked:false,id:39},
          {name:"Jalapano Dip",price:8.91,checked:false,id:40},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
          {name:"Jalapano Dip",price:8.91,checked:false,id:42},
          {name:"Jalapano Dip",price:8.91,checked:false,id:43},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
          {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
        ],
    ],
        minimum_quantity:[2,1,1,null,null],
        counter:[0,0,0,0,0],
        required: [true,true,true,false,false],
        id:4
    },

    {
        meal:"Big Mac",
        price:70.00,
        image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        details:"Mcfest features two 100% fresh burger patties that are hot",
        preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
        preferenceData:[
         [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
            {name:"Jalapano Dip",price:8.91,checked:false,id:12},
            {name:"Jalapano Dip",price:8.91,checked:false,id:13},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
            {name:"Jalapano Dip",price:8.91,checked:false,id:15},
            {name:"Jalapano Dip",price:8.91,checked:false,id:16},
            {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
            {name:"Jalapano Dip",price:8.91,checked:false,id:18},
        ],
          [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
          {name:"Jalapano Dip",price:8.91,checked:false,id:21},
          {name:"Jalapano Dip",price:8.91,checked:false,id:22},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
          {name:"Jalapano Dip",price:8.91,checked:false,id:24},
          {name:"Jalapano Dip",price:8.91,checked:false,id:25},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
          {name:"Jalapano Dip",price:8.91,checked:false,id:27},
        ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
        {name:"Jalapano Dip",price:8.91,checked:false,id:30},
          {name:"Jalapano Dip",price:8.91,checked:false,id:31},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
          {name:"Jalapano Dip",price:8.91,checked:false,id:33},
          {name:"Jalapano Dip",price:8.91,checked:false,id:34},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
          {name:"Jalapano Dip",price:8.91,checked:false,id:36},
        ],

          [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
          {name:"Jalapano Dip",price:8.91,checked:false,id:39},
          {name:"Jalapano Dip",price:8.91,checked:false,id:40},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
          {name:"Jalapano Dip",price:8.91,checked:false,id:42},
          {name:"Jalapano Dip",price:8.91,checked:false,id:43},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
          {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
        ],
    ],
        minimum_quantity:[2,1,1,null,null],
        counter:[0,0,0,0,0],
        required: [true,true,true,false,false],
        id:5
    },

    {
      meal:"Big Mac",
      price:70.00,
      image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      details:"Mcfest features two 100% fresh burger patties that are hot",
      preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
      preferenceData:[
       [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
          {name:"Jalapano Dip",price:8.91,checked:false,id:12},
          {name:"Jalapano Dip",price:8.91,checked:false,id:13},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
          {name:"Jalapano Dip",price:8.91,checked:false,id:15},
          {name:"Jalapano Dip",price:8.91,checked:false,id:16},
          {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
          {name:"Jalapano Dip",price:8.91,checked:false,id:18},
      ],
        [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
        {name:"Jalapano Dip",price:8.91,checked:false,id:21},
        {name:"Jalapano Dip",price:8.91,checked:false,id:22},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
        {name:"Jalapano Dip",price:8.91,checked:false,id:24},
        {name:"Jalapano Dip",price:8.91,checked:false,id:25},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
        {name:"Jalapano Dip",price:8.91,checked:false,id:27},
      ],

      [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
      {name:"Jalapano Dip",price:8.91,checked:false,id:30},
        {name:"Jalapano Dip",price:8.91,checked:false,id:31},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
        {name:"Jalapano Dip",price:8.91,checked:false,id:33},
        {name:"Jalapano Dip",price:8.91,checked:false,id:34},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
        {name:"Jalapano Dip",price:8.91,checked:false,id:36},
      ],

        [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
        {name:"Jalapano Dip",price:8.91,checked:false,id:39},
        {name:"Jalapano Dip",price:8.91,checked:false,id:40},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
        {name:"Jalapano Dip",price:8.91,checked:false,id:42},
        {name:"Jalapano Dip",price:8.91,checked:false,id:43},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
        {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
      ],
  ],
      minimum_quantity:[2,1,1,null,null],
      counter:[0,0,0,0,0],
      required: [true,true,true,false,false],
      id:6
  },
  {
    meal:"Big Mac",
    price:70.00,
    image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    details:"Mcfest features two 100% fresh burger patties that are hot",
    preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
    preferenceData:[
     [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
        {name:"Jalapano Dip",price:8.91,checked:false,id:12},
        {name:"Jalapano Dip",price:8.91,checked:false,id:13},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
        {name:"Jalapano Dip",price:8.91,checked:false,id:15},
        {name:"Jalapano Dip",price:8.91,checked:false,id:16},
        {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
        {name:"Jalapano Dip",price:8.91,checked:false,id:18},
    ],
      [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
      {name:"Jalapano Dip",price:8.91,checked:false,id:21},
      {name:"Jalapano Dip",price:8.91,checked:false,id:22},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
      {name:"Jalapano Dip",price:8.91,checked:false,id:24},
      {name:"Jalapano Dip",price:8.91,checked:false,id:25},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
      {name:"Jalapano Dip",price:8.91,checked:false,id:27},
    ],

    [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
    {name:"Jalapano Dip",price:8.91,checked:false,id:30},
      {name:"Jalapano Dip",price:8.91,checked:false,id:31},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
      {name:"Jalapano Dip",price:8.91,checked:false,id:33},
      {name:"Jalapano Dip",price:8.91,checked:false,id:34},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
      {name:"Jalapano Dip",price:8.91,checked:false,id:36},
    ],

      [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
      {name:"Jalapano Dip",price:8.91,checked:false,id:39},
      {name:"Jalapano Dip",price:8.91,checked:false,id:40},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
      {name:"Jalapano Dip",price:8.91,checked:false,id:42},
      {name:"Jalapano Dip",price:8.91,checked:false,id:43},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
      {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
    ],
],
    minimum_quantity:[2,1,1,null,null],
    counter:[0,0,0,0,0],
    required: [true,true,true,false,false],
    id:7
},

{
  meal:"Big Mac",
  price:70.00,
  image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
  details:"Mcfest features two 100% fresh burger patties that are hot",
  preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
  preferenceData:[
   [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
      {name:"Jalapano Dip",price:8.91,checked:false,id:12},
      {name:"Jalapano Dip",price:8.91,checked:false,id:13},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
      {name:"Jalapano Dip",price:8.91,checked:false,id:15},
      {name:"Jalapano Dip",price:8.91,checked:false,id:16},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
      {name:"Jalapano Dip",price:8.91,checked:false,id:18},
  ],
    [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
    {name:"Jalapano Dip",price:8.91,checked:false,id:21},
    {name:"Jalapano Dip",price:8.91,checked:false,id:22},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
    {name:"Jalapano Dip",price:8.91,checked:false,id:24},
    {name:"Jalapano Dip",price:8.91,checked:false,id:25},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
    {name:"Jalapano Dip",price:8.91,checked:false,id:27},
  ],

  [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
  {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
  {name:"Jalapano Dip",price:8.91,checked:false,id:30},
    {name:"Jalapano Dip",price:8.91,checked:false,id:31},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
    {name:"Jalapano Dip",price:8.91,checked:false,id:33},
    {name:"Jalapano Dip",price:8.91,checked:false,id:34},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
    {name:"Jalapano Dip",price:8.91,checked:false,id:36},
  ],

    [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
    {name:"Jalapano Dip",price:8.91,checked:false,id:39},
    {name:"Jalapano Dip",price:8.91,checked:false,id:40},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
    {name:"Jalapano Dip",price:8.91,checked:false,id:42},
    {name:"Jalapano Dip",price:8.91,checked:false,id:43},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
    {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
  ],
],
  minimum_quantity:[2,1,1,null,null],
  counter:[0,0,0,0,0],
  required: [true,true,true,false,false],
  id:8
},

{
  meal:"Big Mac",
  price:70.00,
  image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
  details:"Mcfest features two 100% fresh burger patties that are hot",
  preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
  preferenceData:[
   [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
      {name:"Jalapano Dip",price:8.91,checked:false,id:12},
      {name:"Jalapano Dip",price:8.91,checked:false,id:13},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
      {name:"Jalapano Dip",price:8.91,checked:false,id:15},
      {name:"Jalapano Dip",price:8.91,checked:false,id:16},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
      {name:"Jalapano Dip",price:8.91,checked:false,id:18},
  ],
    [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
    {name:"Jalapano Dip",price:8.91,checked:false,id:21},
    {name:"Jalapano Dip",price:8.91,checked:false,id:22},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
    {name:"Jalapano Dip",price:8.91,checked:false,id:24},
    {name:"Jalapano Dip",price:8.91,checked:false,id:25},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
    {name:"Jalapano Dip",price:8.91,checked:false,id:27},
  ],

  [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
  {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
  {name:"Jalapano Dip",price:8.91,checked:false,id:30},
    {name:"Jalapano Dip",price:8.91,checked:false,id:31},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
    {name:"Jalapano Dip",price:8.91,checked:false,id:33},
    {name:"Jalapano Dip",price:8.91,checked:false,id:34},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
    {name:"Jalapano Dip",price:8.91,checked:false,id:36},
  ],

    [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
    {name:"Jalapano Dip",price:8.91,checked:false,id:39},
    {name:"Jalapano Dip",price:8.91,checked:false,id:40},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
    {name:"Jalapano Dip",price:8.91,checked:false,id:42},
    {name:"Jalapano Dip",price:8.91,checked:false,id:43},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
    {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
  ],
],
  minimum_quantity:[2,1,1,null,null],
  counter:[0,0,0,0,0],
  required: [true,true,true,false,false],
  id:9
},

{
  meal:"Big Mac",
  price:70.00,
  image:"https://images.unsplash.com/photo-1605262157780-8910063b2bf9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
  details:"Mcfest features two 100% fresh burger patties that are hot",
  preferenceTitle:["Choose 2 dips","Choose your 1st drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour","Choose your 2nd drink flavour"],
  preferenceData:[
   [{name:"Jalapano Dip",price:8.91,checked:false,id:10},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:11},
      {name:"Jalapano Dip",price:8.91,checked:false,id:12},
      {name:"Jalapano Dip",price:8.91,checked:false,id:13},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:14},
      {name:"Jalapano Dip",price:8.91,checked:false,id:15},
      {name:"Jalapano Dip",price:8.91,checked:false,id:16},
      {name:"Sweet and sour Dip",price:8.91,checked:false,id:17},
      {name:"Jalapano Dip",price:8.91,checked:false,id:18},
  ],
    [{name:"Jalapano Dip",price:8.91,checked:false,id:19},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:20},
    {name:"Jalapano Dip",price:8.91,checked:false,id:21},
    {name:"Jalapano Dip",price:8.91,checked:false,id:22},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:23},
    {name:"Jalapano Dip",price:8.91,checked:false,id:24},
    {name:"Jalapano Dip",price:8.91,checked:false,id:25},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:26},
    {name:"Jalapano Dip",price:8.91,checked:false,id:27},
  ],

  [{name:"Jalapano Dip",price:8.91,checked:false,id:28},
  {name:"Sweet and sour Dip",price:8.91,checked:false,id:29},
  {name:"Jalapano Dip",price:8.91,checked:false,id:30},
    {name:"Jalapano Dip",price:8.91,checked:false,id:31},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:32},
    {name:"Jalapano Dip",price:8.91,checked:false,id:33},
    {name:"Jalapano Dip",price:8.91,checked:false,id:34},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:35},
    {name:"Jalapano Dip",price:8.91,checked:false,id:36},
  ],

    [{name:"Jalapano Dip",price:8.91,checked:false,id:37},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:38},
    {name:"Jalapano Dip",price:8.91,checked:false,id:39},
    {name:"Jalapano Dip",price:8.91,checked:false,id:40},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:41},
    {name:"Jalapano Dip",price:8.91,checked:false,id:42},
    {name:"Jalapano Dip",price:8.91,checked:false,id:43},
    {name:"Sweet and sour Dip",price:8.91,checked:false,id:44},
    {name:"Jalapano Dip",price:8.91,checked:false,id:45},  
  ],
],
  minimum_quantity:[2,1,1,null,null],
  counter:[0,0,0,0,0],
  required: [true,true,true,false,false],
  id:10
},
];